# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fakedns < Formula
  desc "Tiny DNS proxy for Penetration Testers and Malware Analysts"
  homepage "https://github.com/hupe1980/fakedns"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hupe1980/fakedns/releases/download/v0.0.8/fakedns_Darwin_arm64.tar.gz"
      sha256 "a6f311271bf8171664d5be02df71a216a4055f48949807b13cc4e6af17de648e"

      def install
        bin.install "fakedns"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/fakedns/releases/download/v0.0.8/fakedns_Darwin_x86_64.tar.gz"
      sha256 "657d35cb028c3b83c1b98e51f412df8f5c2b7e10c40cc6dee511a42345b135fd"

      def install
        bin.install "fakedns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/fakedns/releases/download/v0.0.8/fakedns_Linux_x86_64.tar.gz"
      sha256 "956862073473b787aea695bdc1f95f0c4ac85a87047ef9ef571ff7300f7f3f81"

      def install
        bin.install "fakedns"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/fakedns/releases/download/v0.0.8/fakedns_Linux_armv6.tar.gz"
      sha256 "3a51b7f9ea8e16026f09241c45f501b3560d024518bfc06117450a6f71ea5581"

      def install
        bin.install "fakedns"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/fakedns/releases/download/v0.0.8/fakedns_Linux_arm64.tar.gz"
      sha256 "91439278bfa37287dd4c2854a8f4909161a2816d9b0dab458557abb2bf7d2dbc"

      def install
        bin.install "fakedns"
      end
    end
  end

  test do
    system "#{bin}/fakedns -v"
  end
end
